### ISSUE TITLE
使用部署脚本git pull时，文件权限被篡改

### ISSUE THREAD

**Issue by ericzhao007** [HimiHL/webhook_go#1]
编写git.sh之后，内容只有一行，git pull
1.修改某文件提交，触发webhook执行git.sh 发现文件权限变更为 -rw-r-----

2.修改某文件提交，手动执行git.sh 文件权限未被改变，是预期的 -rw-r--r--

**Comment by HimiHL** [comment]
在git.sh里，再重新设置一次权限

**Comment by ericzhao007** [comment]
尝试过在拉取代码之后批量修改权限，但会引发docker内部的权限问题。没有办法一个一个权限去对

**Comment by ericzhao007** [comment]
问题找到了，将 Umask 设置为0，即可解决

**Comment by HimiHL** [comment]
大佬牛逼！
